### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by avatar789** [Ragebones/StormCore#104]
When compiled on debian 8 produces such errors

/home/mop/StormCore/src/server/scripts/World/npc_innkeeper.cpp: In member function ‘virtual bool npc_innkeeper::OnGossipHello(Player*, Creature*)’:
/home/mop/StormCore/src/server/scripts/World/npc_innkeeper.cpp:64:21: error: ‘class Player’ has no member named ‘ADD_GOSSIP_ITEM’
             player->ADD_GOSSIP_ITEM(GOSSIP_ICON_CHAT, localizedEntry, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
                     ^
/home/mop/StormCore/src/server/scripts/World/npc_innkeeper.cpp:64:37: error: ‘GOSSIP_ICON_CHAT’ was not declared in this scope
             player->ADD_GOSSIP_ITEM(GOSSIP_ICON_CHAT, localizedEntry, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
                                     ^
/home/mop/StormCore/src/server/scripts/World/npc_innkeeper.cpp:71:21: error: ‘class Player’ has no member named ‘ADD_GOSSIP_ITEM’
             player->ADD_GOSSIP_ITEM(GOSSIP_ICON_VENDOR, GOSSIP_TEXT_BROWSE_GOODS, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_TRADE);
                     ^
/home/mop/StormCore/src/server/scripts/World/npc_innkeeper.cpp:71:37: error: ‘GOSSIP_ICON_VENDOR’ was not declared in this scope
             player->ADD_GOSSIP_ITEM(GOSSIP_ICON_VENDOR, GOSSIP_TEXT_BROWSE_GOODS, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_TRADE);
                                     ^
/home/mop/StormCore/src/server/scripts/World/npc_innkeeper.cpp:81:21: error: ‘class Player’ has no member named ‘ADD_GOSSIP_ITEM’
             player->ADD_GOSSIP_ITEM(GOSSIP_ICON_INTERACT_1, localizedEntry, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INN);
                     ^
/home/mop/StormCore/src/server/scripts/World/npc_innkeeper.cpp:81:37: error: ‘GOSSIP_ICON_INTERACT_1’ was not declared in this scope
             player->ADD_GOSSIP_ITEM(GOSSIP_ICON_INTERACT_1, localizedEntry, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INN);
                                     ^
/home/mop/StormCore/src/server/scripts/World/npc_innkeeper.cpp:85:17: error: ‘class Player’ has no member named ‘SEND_GOSSIP_MENU’
         player->SEND_GOSSIP_MENU(player->GetGossipTextId(creature), creature->GetGUID());
                 ^
/home/mop/StormCore/src/server/scripts/World/npc_innkeeper.cpp: In member function ‘virtual bool npc_innkeeper::OnGossipSelect(Player*, Creature*, uint32, uint32)’:
/home/mop/StormCore/src/server/scripts/World/npc_innkeeper.cpp:91:32: error: invalid use of incomplete type ‘class PlayerMenu’
         player->PlayerTalkClass->ClearMenus();
                                ^
In file included from /home/mop/StormCore/src/server/game/Scripting/ScriptMgr.h:25:0,
                 from ScriptPCH.h:8:
/home/mop/StormCore/src/server/game/Quests/QuestDef.h:289:18: error: forward declaration of ‘class PlayerMenu’
     friend class PlayerMenu;
                  ^
/home/mop/StormCore/src/server/scripts/World/npc_innkeeper.cpp:120:21: error: ‘class Player’ has no member named ‘CLOSE_GOSSIP_MENU’
             player->CLOSE_GOSSIP_MENU();
                     ^
/home/mop/StormCore/src/server/scripts/World/npc_innkeeper.cpp:124:17: error: ‘class Player’ has no member named ‘CLOSE_GOSSIP_MENU’
         player->CLOSE_GOSSIP_MENU();
                 ^

**Comment by DJBoxer** [comment]
[#90](https://github.com/Ragebones/StormCore/issues/90) [#91](https://github.com/Ragebones/StormCore/issues/91)

Compile from this [commit](https://github.com/Ragebones/StormCore/tree/efa3af3dd008ce47201c7fcf3fcea2e780c95808)

**Comment by avatar789** [comment]
Nothing Changed

In file included from /home/mop/StormCore/src/server/game/AI/SmartScripts/SmartScript.h:28:0,
                 from /home/mop/StormCore/src/server/game/AI/SmartScripts/SmartAI.h:27,
                 from /home/mop/StormCore/src/server/game/World/World.cpp:70:
/home/mop/StormCore/src/server/game/AI/SmartScripts/SmartScriptMgr.h:298:4: error: ‘unit32’ does not name a type
    unit32 onRemove;
    ^
