### ISSUE TITLE
bnetserver and the worldserver is not working!

### ISSUE THREAD

**Issue by HeldDerZeit** [Ragebones/StormCore#45]
i have tested many versions but the bnetserver and the worldserver is not working ;(

**Comment by Ragebones** [comment]
world server and bnetsever it´s working so xD

**Comment by HeldDerZeit** [comment]
by me come a error

**Comment by Ragebones** [comment]
Probably because you've done something wrong, use discordapp.com/invite/SwnzZWv ifor help if you don't know to set up the emulator.

**Comment by HeldDerZeit** [comment]
0xc000007b come by me and not working and things in my language

**Comment by Ragebones** [comment]
ofcourse 0xc000007b is not a stormcore issue is your machine because he don't read the dll files

**Comment by HeldDerZeit** [comment]
what dll files?

**Comment by DJBoxer** [comment]
Try reading this https://trinitycore.atlassian.net/wiki/display/tc/Application+Error%3A+0xc000007b 

This is User issue not with Stormcore !!
