### ISSUE TITLE
Online server issue

### ISSUE THREAD

**Issue by greatmemar** [Ragebones/StormCore#68]
I am running the server on Windows Server 2012 R2 Datacenter Edition (64 Bit), everything looks running fine without any error but I am not able to connect the server from my PC, I change the Auth/realmlist table address to my VPS host IP address
Here is the image of the server:
https://ibb.co/ez89Ov
Please tell me help.

**Comment by DJBoxer** [comment]
Did you use connection patcher on wow.exe ? also checked to see your ports are open. Also are your receiving any error from client.

**Comment by SilvioDoMine** [comment]
Which error you get? As @DJBoxer said, is probably that you're not using a patched wow.exe, try to patch using the connection_patcher.bat

**Comment by BattleSheep94** [comment]
did you change the IP's in the configs?

and the screenshot has not the best resolution ^^

**Comment by greatmemar** [comment]
Thank you so much for replaying
@DJBoxer yeah I use the connection patcher on wow.exe, I am not sure about the port but as it is VPS host I think all the ports should be open by default? The server does not have any error but the client giving this error: "you have been disconnected (blz51900002)."
@SilvioDoMine I patched wow.exe, it is working fine in my localhost server but in VPS host it is not working.
@Fameling in WTF/config.wtf I changed SET portal "5.189.179.169"

**Comment by greatmemar** [comment]
This is how I set Auth->realmlist table:
http://imgur.com/a/aqSg1

**Comment by greatmemar** [comment]
I run netstat -an on the server, the port 8085 is under LISTENING
http://imgur.com/a/JaQ5B
and I checked the port with online tools it say it is open:
http://imgur.com/a/b5WHg

**Comment by edward4885** [comment]
Do you allow logon and world from firewall ?

**Comment by DJBoxer** [comment]
I see your auth realm is fine in DB and your port 8085 is open.
How about your login port 8081? As I believe the error "you have been disconnected (blz51900002)." is due to login basically client cant connect. So  I'm guessing maybe try checking there I see its bind to 0.0.0.0 maybe change it to match realm ip an check its port. Its just my guess

**Comment by greatmemar** [comment]
@edward4885 what is lagon? I only gave access for bnetserver and worldserver

**Comment by greatmemar** [comment]
@DJBoxer I opened port 8081 but still save error

**Comment by DJBoxer** [comment]
There is only one more thing I can think of and that's to check your bnetserver.conf.

check these lines:

LoginREST.Port = 8081      //check to see if open ?
LoginREST.ExternalAddress=127.0.0.1   //possible maybe change this or check this to be your external ?
LoginREST.LocalAddress=127.0.0.1   //this shouldn't need to be changed.

maybe try above and ofcourse just restart your server.

only other thing maybe change:
BindIP = "0.0.0.0"    I know it binds to all but maybe set to external??

**Comment by greatmemar** [comment]
@DJBoxer thank you, the issue was this "LoginREST.ExternalAddress=127.0.0.1 //possible maybe change this or check this to be your external ?"

**Comment by DJBoxer** [comment]
you`re welcome. glad you solved this issue I'm sure it was frustrating.

kind regards,

@Ragebones Solved please close..
